database:
  type: SQLite

  # MySQL
  host: "127.0.0.1"
  port: 3306
  username: NullProtect
  password: NullProtect
  database: NullProtect

# Thread pool settings
async:
  # fixed or virtual
  mode: fixed

  # Core pool size
  core: 10
  # Max threads
  max: 30

hwid:
  enabled: false

  # Timeout check interval (seconds)
  check-interval: 10
  # Timeout (seconds)
  timeout: 10

  # Enable HWID binding
  bind: false
  # whitelist or blacklist or none
  mode: none
  # Commands to execute on blacklist triggered or added when target player is online
  on-blacklist:
    - "ban %player% HWID banned from this server"

activation:
  enabled: false
  # Timeout (seconds)
  timeout: 10

  # Block actions if not activated
  blocking:
    chat: true
    move: true
    interact: true

# Fake plugin commands
fake:
  enabled: true
  # Fake version command tab-completes
  fake-version: true
  # Append fake plugin names to version command
  # Also creates fake version messages
  fake-version-plugins:
    NotProtect:
      author: AFterNode
      version: 114.514
  # Hide NullProtect
  hide-self: true

# Mods hash check
mods:
  enabled: false

  # Timeout check interval (seconds)
  check-interval: 10
  # Timeout (seconds)
  timeout: 10
