database:
  type: SQLite

  # MySQL
  host: "127.0.0.1"
  port: 3306
  username: NullProtect
  password: NullProtect
  database: NullProtect

# Thread pool settings
async:
  # fixed or virtual
  mode: fixed

  # Core pool size
  core: 10
  # Max threads
  max: 30

hwid:
  enabled: false

  # Timeout check interval (seconds)
  check-interval: 10
  # Timeout (seconds)
  timeout: 10

  # Enable HWID binding
  bind: false
  # whitelist or blacklist or none
  mode: none
  # Commands to execute on blacklist triggered or added when target player is online
  on-blacklist:
    - "ban %player% HWID banned from this server"

activation:
  enabled: false
  # Timeout (seconds)
  timeout: 10

  # Block actions if not activated
  blocking:
    chat: true
    move: true
    interact: true

# Fake plugin commands
fake:
  enabled: true
  # Fake version command tab-completes
  fake-version: true
  # Append fake plugin names to version command
  # Also creates fake version messages
  fake-version-plugins:
    NotProtect:
      author: AFterNode
      version: 114.514
  # Hide NullProtect
  hide-self: true

# Mods hash check
mods:
  enabled: false

  # Timeout check interval (seconds)
  check-interval: 10
  # Timeout (seconds)
  timeout: 10

# Ingame captcha
captcha:
  enabled: false

  chest: true # Classic chest item click
  furnace: true # Furnace slot click
  book: true # Colored text click
  image: false  # (BETA) Enable image captcha, will create lots of maps, supports 128*128 images only

  # Minimum interval (seconds) for auto captcha
  min-interval: 600
  # Timeout (seconds)
  timeout: 30

  # Auto trigger probability for per event (1-100)
  auto:
    lumbering: 5
    mining: 5
    mining_deepslate: 5
    fishing: 10

# EULA
eula:
  enabled: false

  # text, external or manually
  # In TEXT mode, the book configured below (text) will be opened for the player
  # In EXTERNAL mode, a message with a URL configured below (link) will be sent to the player
  # In MANUALLY mode, you need to manually implement the EULA interface and save only the status and processing operations
  mode: text
  # Book contents for text mode
  # MiniMessage formats
  text:
    - |
      PAGE 1
      LINE 2
    - |
      PAGE 2
      LINE 2
  # Link for external mode
  link: "https://github.com/"
