modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "nullprotect"
version = "${version}"
displayName = "NullProtect"
authors = "ArcNode"
description = '''
Server protection suit
'''
#logoFile = ""

[[dependencies.nullprotect]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nullprotect]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "nullprotect.mixins.json"
