package arcnode.nullprotect.server.paper.commands

import arcnode.nullprotect.server.paper.listeners.AccountActivationListener
import arcnode.nullprotect.server.paper.plugin
import cn.afternode.commons.bukkit.kotlin.BaseCommand
import cn.afternode.commons.bukkit.kotlin.message
import org.bukkit.command.CommandSender
import org.bukkit.entity.Player

object ActivateCommand: BaseCommand("activate") {
    private val usage by lazy { plugin.context.message {
        text("Usage: activate [code]")
    } }
    private val invalidCode by lazy { plugin.context.message {
        text("Invalid activation code")
    } }
    private val alreadyActivated by lazy { plugin.context.message {
        text("Account already activated")
    } }
    private val completed by lazy { plugin.context.message {
        text("Account activated successful")
    } }

    override fun exec(sender: CommandSender, vararg args: String) {
        if (sender !is Player) {    // Player-only command
            sender.sendMessage(MSG_PLAYER_ONLY)
        } else if (args.size != 1) {    // Invalid parameters
            sender.sendMessage(usage)
        } else {
            val code = args[0]
            if (code.length == 32) {
                plugin.runBlockingCoroutine { activateAsync(sender, code) }
            } else {    // Invalid code
                sender.sendMessage(invalidCode)
            }
        }
    }

    private suspend fun activateAsync(player: Player, code: String) {
        if (plugin.database.accountActivation.find(player.uniqueId) != null) {  // Already activated
            player.sendMessage(alreadyActivated)
            return
        }

        val codeModel = plugin.database.accountActivationCode.get(code)
        if (codeModel == null) {    // Invalid code
            player.sendMessage(invalidCode)
        } else {    // Activate
            plugin.database.accountActivation.add(player.uniqueId, code)
            plugin.database.accountActivationCode.remove(code)
            plugin.slF4JLogger.info("(${player.name}) Activated with \"$code\" (Generated by \"${codeModel.by}\")")
            AccountActivationListener.onActivated(player.uniqueId)
            player.sendMessage(completed)
        }
    }
}